resources:
  - name: script-repo
    type: git
    source:
      uri: https://github.com/kristianstanchev/sap.git
      branch: master
      username: ((github-username))
      password: ((github-token))
  - name: every-5-minutes
    type: time
    source:
      interval: 5m
  - name: tutorial
    type: docker-image
    source:
      repository: kristianstanchev/tutorial
      tag: v1
jobs:
  - name: task1_hello_sap
    public: true
    plan:
      - get: every-5-minutes
        trigger: true
      - task: simple-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: echo
            args: ["Hello SAP!"]
  - name: task2_run_script_from_git
    plan:
      - get: every-5-minutes
        trigger: true
      - get: script-repo
      - task: execute-script
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          inputs:
            - name: script-repo
          run:
            path: /bin/sh
            args:
              - -c
              - |
                echo "Executing script from Git"
                chmod +x script-repo/task2.sh
                sh ./script-repo/task2.sh
  - name: task4_run_docker_scripts
    plan:
      - get: every-5-minutes
        trigger: true
      - get: tutorial
      - get: script-repo
      - task: process-yaml-json
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: kristianstanchev/tutorial
              tag: v1
          inputs:
            - name: script-repo
          run:
            path: /bin/sh
            args:
              - -c
              - |
                echo "Using custom Docker image!"
  - name: task5_run_personas_scripts
    plan:
      - get: every-5-minutes
        trigger: true
      - get: tutorial
      - get: script-repo
      - task: process-yaml-json
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: kristianstanchev/tutorial
              tag: v1
          inputs:
            - name: script-repo
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd script-repo
                chmod +x personas.json
                chmod +x process_personas.py
                chmod +w greeted_people.json
                chmod +x greeted_people.json
                python3 process_personas.py