jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      image_resource:
        name: ""
        source:
          password: ((concourse-docker-image-password))
          repository: iacbox.common.repositories.cloud.sap/iacbox2
          tag: v699
          username: ((concourse-docker-image-username))
        type: registry-image
      platform: linux
      run:
        path: echo
        args: ["Hello, world!"]